#!/bin/bash


wget ftp://ftp.mpi-sb.mpg.de/pub/gnu/mirror/gcc.gnu.org/pub/gcc/releases/gcc-4.8.2/gcc-4.8.2.tar.gz

tar -xvvf gcc-4.8.2.tar.gz

rm gcc-4.8.2.tar.gz

mkdir GCC-install

mv gcc-4.8.2/ GCC-install/

cd GCC-install/

cd gcc-4.8.2

mkdir build

cd build

../configure --prefix=/u/aureooms/GCC-install/

make

# make check

make install

cd ~

ln -s ~/GCC-install/bin/g++ ~/g++