#!/bin/bash

wget http://www.freestatistics.org/cran/src/contrib/Rmpi_0.6-3.tar.gz

./R CMD INSTALL Rmpi_0.6-3.tar.gz --configure-args="--with-Rmpi-include=/u/aureooms/MPICH-install/include/ --with-Rmpi-libpath=/u/aureooms/MPICH-install/lib/ --with-Rmpi-type=MPICH2"



# ./R CMD INSTALL Rmpi_0.6-3.tar.gz --configure-args="--with-Rmpi-include=/adm/nodes/opt/platform_mpi/include/ --with-Rmpi-libpath=/adm/nodes/opt/platform_mpi/lib/linux_amd64/ --with-Rmpi-type=OPENMPI"


# ./R CMD INSTALL Rmpi_0.6-3.tar.gz --configure-args="--with-Rmpi-include=/adm/nodes/opt/platform_mpi/MPICH2.0/include/ --with-Rmpi-libpath=/adm/nodes/opt/platform_mpi/MPICH2.0/lib/linux_amd64/ --with-Rmpi-type=OPENMPI"