#!/bin/bash -l
#PBS -l nodes=4:ppn=8
#PBS -l walltime=48:00:00
#PBS -l mem=1gb
#PBS -j oe
#PBS -N tuning-pfsp-sa
#PBS -o log/tuning-pfsp-sa
echo "Running job on $HOST - " ‘date‘
cd ~/infoh413
make COMPILER=~/g++ O=3 nocolor=true EMBED=~/GCC-install/lib/
cd tuning/pfsp-sa
~/irace
echo "Done"
