#!/bin/bash -l
#PBS -l nodes=1:ppn=1
#PBS -l walltime=48:00:00
#PBS -l mem=1gb
#PBS -j oe
#PBS -N tuning-pfsp-ig
#PBS -o log/tuning-pfsp-ig
echo "Running job on $HOST - " ‘date‘
cd ~/infoh413

module load openmpi/1.6.5/gcc/4.8.2
module load R/3.0.2
module unload gcc/4.6.1/gcc/4.4.7 || true
module unload gdb/7.7/gcc/4.4.7 || true

make nocolor=true
cd tuning/pfsp-ig
~/irace
echo "Done"
