#!/bin/sh

T=$(date +"%m%d%H%M")$1
shift

ls data/in/50x20_* | python3 do/bench.py gen ./run/pfsp-ii -- data/out/$T/ii "$@" json/opt.json
ls data/in/50x20_* | python3 do/bench.py gen ./run/pfsp-vnd -- data/out/$T/vnd "$@" json/opt.json