#!/bin/sh

T=$(date +"%m%d%H%M")$1

python3 do/fake.py -q ./run/pfsp-ig data/in/ data/out/$T-corr/ig json/opt_corr.json 0 1 2 3 4
python3 do/fake.py -q ./run/pfsp-tabu data/in/ data/out/$T-corr/tabu json/opt_corr.json 0 1 2 3 4


python3 do/fake.py -v ./run/pfsp-ig data/in/ data/out/$T-qrd/ig json/opt_qrd.json 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
python3 do/fake.py -v ./run/pfsp-tabu data/in/ data/out/$T-qrd/tabu json/opt_qrd.json 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24