#!/bin/sh

mkdir -p data/corr/"$1"

echo data/corr/"$1"50x20
python3 do/corr.py data/dev/"$1"50x20/ data/corr/"$1"50x20.svg
echo data/corr/"$1"60x20
python3 do/corr.py data/dev/"$1"60x20/ data/corr/"$1"60x20.svg
echo data/corr/"$1"70x20
python3 do/corr.py data/dev/"$1"70x20/ data/corr/"$1"70x20.svg
echo data/corr/"$1"80x20
python3 do/corr.py data/dev/"$1"80x20/ data/corr/"$1"80x20.svg
echo data/corr/"$1"90x20
python3 do/corr.py data/dev/"$1"90x20/ data/corr/"$1"90x20.svg
echo data/corr/"$1"100x20
python3 do/corr.py data/dev/"$1"100x20/ data/corr/"$1"100x20.svg