#!/bin/sh

python3 do/dev.py data/out/ data/best/ data/dev/ "$1" 50x20
python3 do/dev.py data/out/ data/best/ data/dev/ "$1" 60x20
python3 do/dev.py data/out/ data/best/ data/dev/ "$1" 70x20
python3 do/dev.py data/out/ data/best/ data/dev/ "$1" 80x20
python3 do/dev.py data/out/ data/best/ data/dev/ "$1" 90x20
python3 do/dev.py data/out/ data/best/ data/dev/ "$1" 100x20