#!/bin/sh

mkdir -p data/report/"$1"

echo data/report/"$1"50x20
python3 do/report.py data/out/"$1" data/best/ 50x20 4 > data/report/"$1"50x20
echo data/report/"$1"60x20
python3 do/report.py data/out/"$1" data/best/ 60x20 4 > data/report/"$1"60x20
echo data/report/"$1"70x20
python3 do/report.py data/out/"$1" data/best/ 70x20 4 > data/report/"$1"70x20
echo data/report/"$1"80x20
python3 do/report.py data/out/"$1" data/best/ 80x20 4 > data/report/"$1"80x20
echo data/report/"$1"90x20
python3 do/report.py data/out/"$1" data/best/ 90x20 4 > data/report/"$1"90x20
echo data/report/"$1"100x20
python3 do/report.py data/out/"$1" data/best/ 100x20 4 > data/report/"$1"100x20