#!/bin/sh

mkdir -p data/stat/"$1"

cat data/test/"$1"50x20 | python3 do/stat.py > data/stat/"$1"50x20
cat data/test/"$1"60x20 | python3 do/stat.py > data/stat/"$1"60x20
cat data/test/"$1"70x20 | python3 do/stat.py > data/stat/"$1"70x20
cat data/test/"$1"80x20 | python3 do/stat.py > data/stat/"$1"80x20
cat data/test/"$1"90x20 | python3 do/stat.py > data/stat/"$1"90x20
cat data/test/"$1"100x20 | python3 do/stat.py > data/stat/"$1"100x20