#!/bin/sh

mkdir -p data/stat/"$1"

echo data/stat/"$1"50x20
cat data/test/"$1"50x20 | python3 do/stat.py 50x20 > data/stat/"$1"50x20
echo data/stat/"$1"60x20
cat data/test/"$1"60x20 | python3 do/stat.py 60x20 > data/stat/"$1"60x20
echo data/stat/"$1"70x20
cat data/test/"$1"70x20 | python3 do/stat.py 70x20 > data/stat/"$1"70x20
echo data/stat/"$1"80x20
cat data/test/"$1"80x20 | python3 do/stat.py 80x20 > data/stat/"$1"80x20
echo data/stat/"$1"90x20
cat data/test/"$1"90x20 | python3 do/stat.py 90x20 > data/stat/"$1"90x20
echo data/stat/"$1"100x20
cat data/test/"$1"100x20 | python3 do/stat.py 100x20 > data/stat/"$1"100x20