#!/bin/sh

mkdir -p data/test/tim/"$1"

echo data/test/tim/"$1"50x20
python3 do/test.py data/tim/"$1"50x20/ > data/test/tim/"$1"50x20
echo data/test/tim/"$1"60x20
python3 do/test.py data/tim/"$1"60x20/ > data/test/tim/"$1"60x20
echo data/test/tim/"$1"70x20
python3 do/test.py data/tim/"$1"70x20/ > data/test/tim/"$1"70x20
echo data/test/tim/"$1"80x20
python3 do/test.py data/tim/"$1"80x20/ > data/test/tim/"$1"80x20
echo data/test/tim/"$1"90x20
python3 do/test.py data/tim/"$1"90x20/ > data/test/tim/"$1"90x20
echo data/test/tim/"$1"100x20
python3 do/test.py data/tim/"$1"100x20/ > data/test/tim/"$1"100x20