#!/bin/sh

mkdir -p data/test/"$1"

python3 do/test.py data/dev/"$1"50x20/ > data/test/"$1"50x20
python3 do/test.py data/dev/"$1"60x20/ > data/test/"$1"60x20
python3 do/test.py data/dev/"$1"70x20/ > data/test/"$1"70x20
python3 do/test.py data/dev/"$1"80x20/ > data/test/"$1"80x20
python3 do/test.py data/dev/"$1"90x20/ > data/test/"$1"90x20
python3 do/test.py data/dev/"$1"100x20/ > data/test/"$1"100x20