#!/bin/sh

python3 do/tim.py data/out/ data/tim/ "$1" 50x20
python3 do/tim.py data/out/ data/tim/ "$1" 60x20
python3 do/tim.py data/out/ data/tim/ "$1" 70x20
python3 do/tim.py data/out/ data/tim/ "$1" 80x20
python3 do/tim.py data/out/ data/tim/ "$1" 90x20
python3 do/tim.py data/out/ data/tim/ "$1" 100x20